config/routes.rb
Rails.application.routes.draw do

  
  root 'page#home'

  get 'page/about'

  get 'page/contact'

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kpath</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id = "navigation">
	<div id="nav_wrapper">
		<ul>
		  <li><a><%= link_to "HOME", root_path%></a></li>
		  <li><a><%= link_to "ABOUT", page_about_url%></a></li>
		  <li><a><%= link_to "MISC", page_contact_url%></a></li>
		</ul>
	</div>
</div>

<%= yield %>

</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kpath</title>
  <%= stylesheet_link_tag 'home.css' %>
  <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Jaldi|Shrikhand" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

</head>
<body>
<div class="video_container">
<video poster="long.jpg" autoplay="true" loop>
		<source src="https://s3.amazonaws.com/distill-videos/videos/processed/34/BetweenTwoTrees-HD.mp4.webm" type="video/webm">
		<source src="https://s3.amazonaws.com/distill-videos/videos/processed/34/BetweenTwoTrees-HD.mp4-mobile.mp4" type="video/mp4">
	</video>

	<div class="text_logo">KARROT PATH</div>
	<div class="arrow"><a href="#main"><img src="/assets/down.png"></img></a></div>
	<div class="pulse-ring"></div>

</div>

<div id="main"> 
	<div class="main_title"><h1>SEE WHAT <span style="color: #F64005">PATHS</span> LIE AHEAD</h1></div>
	<div class="main_organization">
		<h1><span style="color: #F64005">O</span>rganization<h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  		
	</div>
	<div class="main_volunteer">
		<h1><span style="color: #F64005">V</span>olunteer<h1>
		<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
	<div class="buttons">
		<div class="org_button"><p>Learn More</p></div>
		<div class="vol_button"><p>Learn More</p></div>
	</div>
</div>
<script>
$(document).ready(function(){
  $("a").on('click', function(event) {
    if (this.hash !== "main") {
      event.preventDefault();
      var hash = this.hash;

      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 1700, function(){
   
        window.location.hash = hash;
      });
    } 
  });
});
</script>
</body>
</html>